### ISSUE TITLE
Missing privacy manifest file

### ISSUE THREAD

**Issue by cicerocamargo** [persona-id/inquiry-ios-2#5]
Hello everyone! 
This is Cicero speaking in behalf of [Airtm](https://airtm.com)'s Tech team.

As we prepare for the upcoming enforcement of Apple's requirement for a privacy manifest in iOS apps and SDKs **starting from May 1st**, we've been reviewing our integrations, particularly with regards to our most sensitive SDKs. Among these, `PersonaInquirySDK2` stands out, as it collects a lot of personal data from the user but currently does not include a privacy manifest.

We understand the importance of compliance with these guidelines and wanted to inquire whether you are currently working on updating your SDK to include the required privacy manifest. Alternatively, if there is a version of the framework with this information that is not publicly available yet, we would greatly appreciate any insight or assistance you can provide on this matter.

Thanks in advance.
Best regards,
Cícero

**Comment by daniel-e-gonzalez** [comment]
Hi Cicero,

I believe someone from our account team reached out to you regarding this. Just wanted to close this out with the following information.

If you update to at least v2.18.1 of our iOS SDK, you should now be getting our privacy manifest. Note that we did not add everything that our SDK can collect since our SDK functionality depends on how an organization has configured our software. We only added the items we collect by default for all inquiry flows. You'll want to add items to your privacy manifest depending on how you are using our SDK. We have put together a guide [here](https://docs.withpersona.com/docs/ios-privacy-manifest) with more information.

**Comment by cicerocamargo** [comment]
Hi @daniel-e-gonzalez! 
Yes, people from Persona reached out directly via Slack.
Thank you very much for the update.
