### ISSUE TITLE
Inconsistent PersonaInlineNavigationState and duplicate delegate calls in PersonInlineViewController

### ISSUE THREAD

**Issue by protocorn93** [persona-id/inquiry-ios-2#8]
Hello again 😅 

I’m currently integrating `PersonInlineViewController` into my app flow because I need inline functionality.

Following my previous report, the access control of the `PersonaInlineNavigationState` properties was updated, allowing me to adjust the navigation bar button items in my `UINavigationController`. However, I’ve encountered an issue where the `PersonaInlineNavigationState` returned by the delegate method behaves inconsistently.

In the attached video, when navigating back from the Upload Photo ID screen to the Country Selection screen, the `PersonaInlineNavigationState` returned by the delegate method is irregular. I expect `backButtonEnabled` to be `true`, but it is often returned as `false`. Occasionally, it does return `true` as expected, but only sporadically.

Additionally, even though I only call the back method once, the delegate method is sometimes called twice unexpectedly.

I have attached a video demonstrating the issue.

Should the inline flow be avoided for now?

Thank you for looking into this!

**Comment by jacoblange-dev** [comment]
hey sorry for slow response.

I'll write a quick sample implementation in our public demo app.

> the delegate method is sometimes called twice unexpectedly.
this sounds like it might be a leaked handler? I can test though.

> Should the inline flow be avoided for now?
to be honest, you are the first to attempt to integrate with it 😅 I can help you work out the issues with it and it should be fine to use.

**Comment by jacoblange-dev** [comment]
ok I'm going to push some fixes out soon. the main issue is a race between https://developer.apple.com/documentation/uikit/uinavigationcontroller/setviewcontrollers(_:animated:) and https://developer.apple.com/documentation/uikit/uinavigationcontroller/topviewcontroller. it turns out topViewController depends on when the animation completes (even though viewControllers has already been changed). additionally there's some padding issues when using inline mode that I'm going to correct.

> Additionally, even though I only call the back method once, the delegate method is sometimes called twice unexpectedly.

this is actually expected after testing, reason being is we first navigate to a loading view controller then we navigate to the previous step. because our flow is dynamic, the server determines the where the flow goes when the user decides to go back, so we need a loading screen while we make a network request. when navigating forward, we usually keep the loading state on the same screen (this doesn't work as well for back buttons).

**Comment by protocorn93** [comment]
I understand. I believe that if the inline feature can be used, we can create a more seamless identity verification flow within our app. Currently, I don't have control over the screen when the process is completed, canceled, or encounters an error, which feels a bit unnatural. I hope the inline feature stabilizes soon.

Thanks

**Comment by jacoblange-dev** [comment]
hello, sorry I wasn't able to follow up sooner. We published a fix for the duplicate state issue today in v2.25.2. Additionally, I've implemented an example project that showcases how to use inline mode https://github.com/persona-id/persona-ios-sdk/compare/main...jacob/inline-example
